name: Deploy to GitHub Pages

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Build
      run: |
         npm install -g @angular/cli
         npm install
         ng build --prod --base-href /diy-flightcase-calculator/
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.5.5
      with:
        BRANCH: gh-pages
        FOLDER: dist/diy-flightcase-calculator
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: master